### PR TITLE
fix: non-alphabetical characters are removed

### LINKED ISSUE #32: to_snake_case breaks with numbers
```
Group1
```
became with `gas`
```
group_
```

### LINKED ISSUE #34: Breaks on single all caps token
I wanted to convert `BACKSLASH` to `Backslash` with `gap` but it did nothing, and `gas` yielded `b_a_c_k_s_l_a_s_h`.

### PR DESCRIPTION
**Pull request by aznhe21**
I have rewritten the string parsing code to fix the issue with removing non-alphabetic characters. Additionally, all-capitalized words will no longer be split.

This PR fixes #32 and fixes #34, and also partially addresses #23.

### CODE REVIEW

**Comment by johmsalas** [comment]
It looks interesting, it is working so far, I'm run your branch some days before merging
Sorry for the late response, just recently started to code again

**Review by johmsalas — APPROVED** [review]

**Comment by peterfication** [comment]
@aznhe21 I just introduced a CI pipeline which also added a StyLua check. This means a lot of files/lines were touched for the initial StyLua run. Can you please rebase your PR with the latest version of the main branch?

**Review by peterfication — APPROVED** [review]
@johmsalas these changes look good to me and are covered with tests that pass in CI. Some manual testing on my machine worked fine. So I'd say you can merge them in.

**Comment by johmsalas** [comment]
I've been using Hiro's branch for a while with no issues
It's mid-day for me, if someone reports an issue I can revert it. 

This PR solves several things. Going to merge it

**Pull request merged**
