### PR TITLE
Apply each case to its keybinding description

### LINKED ISSUE #38: Request: improve keymap descriptions by using the case the mapping will apply in the description (e.g., `Convert toCamelCase`)
Hi there! Thanks for the plugin! I have a feature request if you're open to them.

The descriptions for the default keymappings currently look like this:

image

This would be more intuitive if each mapping showed the case it will apply. For example:

- `Convert toCamelCase`
- `Convert to-dash-case`

And so on.

It's possible this could be automatically done simply by calling the function that underlies the mapping on `to*` part of the description when the mappings are being generated.

### PR DESCRIPTION
**Pull request by mmirus**
Closes #38 

Before:

image

After:

image

### CODE REVIEW

**Comment by mmirus** [comment]
:wave: Hey @johmsalas! Please let me know if this needs changes, if you have a chance to take a look at it. Hope it is a useful change!

**Review by johmsalas — APPROVED** [review]
I noticed this was an issue just a couple of days before your PR

Thanks for fixing it

**Comment by johmsalas** [comment]
Hey @mmirus !

You already noticed we had to rollback. I think a quick win on this topic would be to verified if the function is defined and use it if that's the case, otherwise, just keep the ugly desc

https://github.com/johmsalas/text-case.nvim/issues/40#issuecomment-1499453178

wdyt?

**Comment by mmirus** [comment]
Hey @johmsalas! I gave that a shot yesterday and it didn't seem like it solved the problem.

Here's the line that's throwing the error: https://github.com/johmsalas/text-case.nvim/blob/cd7cc65a412beb713e68f3b84e45990a939b7b6b/lua/textcase/plugin/plugin.lua#L193.

And right above that, we have https://github.com/johmsalas/text-case.nvim/blob/cd7cc65a412beb713e68f3b84e45990a939b7b6b/lua/textcase/plugin/plugin.lua#L192.

My best guess is that it's trying to find the method on line 192 using the desc, but we modified the desc for display, so it no longer matches the lookup and is nil.

If that's correct, then we'd need to separate the way of looking up the method from the desc in order to support the kind of descriptions we're trying to achieve.

I wasn't sure where to start looking to try to decouple that with the time I had available.

**Pull request merged**
