### PR TITLE
Change description format to reflect its action

### PR DESCRIPTION
**Pull request by peterfication**
So you see what you get:

Screenshot 2023-10-25 at 08 51 12

### CODE REVIEW

**Review by johmsalas — APPROVED** [review]
Thanks!

**Comment by peterfication** [comment]
Will you merge it? I can't merge it, because "Only those with write access to this repository can merge pull requests."

**Comment by johmsalas** [comment]
🤦‍♂️ was wondering that

**Comment by johmsalas** [comment]
@peterfication may you have a look on this please? https://github.com/johmsalas/text-case.nvim/issues/49

It is possible to checkout the branch on you local instance to do some testing. Let me know if you require instructions in the setup

https://github.com/johmsalas/text-case.nvim/issues/49

**Pull request merged**
